### PR TITLE
Further improve the intro

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by ChristianGruen** [comment]
Very good to read! Two brief questions (mostly to check my English skills):
* Due to the pronouncation of H as /eɪtʃ/, I wrote »An HTTP client«. As you chose to write »A HTTP client«; maybe I missed something here?
* Is it common to use a dot after »via«?

**Comment by adamretter** [comment]
So...

> * Due to the pronouncation of H as /eɪtʃ/, I wrote »An HTTP client«. As you chose to write »A HTTP client«; maybe I missed something here?

Your grasp of the technicalities of the English language is likely better than mine! As a Native English speaker, "A HTTP Client" sounds correct to me, but I cannot explain why, apart from to say that "An HTTP Client" does not fit here. Not very useful I know!

I had to ask @joewiz about this, as he is my source for all things language related.
IMHO there is lots of confusing information out there, from what I can discern (probably poorly), it all comes down to whether you pronounce the capital letter `H` as either `haych` or `aych`?
If it is `haych` you need to use `a` before it, if it is `aych` you need to use `an` before it.

In practice both pronunciations are used throughout the UK. Personally I pronounce it `haych`, although that seems to be in the minority, and that that `acych` is the preferred pronunciation. It is likely that this is a regional dialect thing.

So the advice here would seem to be that `H` is `aych`, and that we should use `an`, even if it sounds strange to my untrained ear.

Many thanks to @joewiz for investigating this :-)

> Is it common to use a dot after »via«?
Nope. That is a wrong, and a nasty habit I have picked up! It should be just "via".

I will make some fixes to the PR...

**Comment by adamretter** [comment]
@ChristianGruen okay I fixed and rebased those mistakes

**Comment by ChristianGruen** [comment]
Thanks so much for the comprehensive clarification, Adam ;)

**Pull request merged**
