### PR TITLE
Added an option for preemptive authentication

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by ChristianGruen** [comment]
I must confess I would require more details to implement this by myself (and I would probably expect the specification to give me at least some more information). Should we postpone this to version 2.1 or 3 of the spec?

**Comment by adamretter** [comment]
It was actually in the EXPath HTTP Client 1.0... but it had the absolutely misleading and confusing name of `send-authorization` - http://expath.github.io/expath-cg/specs/http-client/#authentication

From an eXist perspective we need this in the spec as I discovered last week we do have users already using it with HTTP Client 1.0.

In terms of implementation, it can only be used with BASIC authentication. It just means that you should send the HTTP-Authentication header on the first request to the server, as opposed to sending a request, waiting for the server to respond with a authentication challenge, and then resending the request with the HTTP-Authentication header.

**Comment by ChristianGruen** [comment]
I got it, 👍 for the clarification!

It has not been expressed clearly in the spec, but I would have proposed anyway that, in order to reduce the number of required requests, we use preemptive authentication whenever possible. One should never try to send authentication data if the server does not require it – and if it’s required, we’ll need to send it anyway in the second request. Today, basic authentication should never be used without https/ssl anyway,  so I am not sure if there are still any advantages for disabling preemptive authentication at all?

Thanks to your explanation, I noticed we implemented this wrong for version 1 of the spec; probably because of the misleading name of the option (but I see that the old spec indicates clearly how this was supposed to work, so we should have spent more time in reading the details). Indeed, we only evaluated supplied authentication data if the option was enabled. When creating the request, we were always choosing preemptive authentication (https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/util/http/HttpClient.java#L105-L141).

The specification already states that “Authentication data is processed if a non-empty username is supplied”. Would you mind enabling preemptive authentication in all cases, and relieving the user from taking care about further details of the authentication procedure?

**Comment by adamretter** [comment]
> I noticed we implemented this wrong for version 1 of the spec; probably because of the misleading name of the option

Indeed. The naming in the HTTP Client spec 1.0 for this leads to confusion. Some of our eXist-db users have also questioned it in the past.


> Would you mind enabling preemptive authentication in all cases

I really don't want to enable it by default.
There are still many non-SSL resources out there. I rather tend to agree with the advice here - https://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html#d5e717

**Comment by adamretter** [comment]
Regards `http://a:b@c/de`, I don't do anything specific, I just pass it into the Apache Http Client. I actually don't know what its order of preference is for the URL with credentials vs. explicit credentials. No one has ever asked me before!

**Comment by fgeorges** [comment]
Yes, it is necessary to prevent having the back-and-forth requests (1st resulting in 401 then sending credentials) but cannot be enabled by default for security reasons.

About the naming, it comes from the XProc `c:http-request` option with the same name (this step was the only one providing this functionality in the X* recommendations at the time and was thus the inspiration).  It might be slightly confusing without reading its definition :-) (which means rather "I'm gonna send authorization straight away without even knowing the security context, I gotta trust you on this, man")

**Comment by ChristianGruen** [comment]
Thanks both for your assessments. – I’m summarizing some of my findings here, just to have them publicly documented:

* I noticed that some existing HTTP clients seem to skip the authentication challenge (such as `curl`), others don’t (such as `wget`, which provides a `no-auth-challenge` option). But I can understand that it makes sense to remain faithful to the design choices of the original RFC.
* There seem to be approaches to providing preemptive authentication for Digest authentication in the web, but I can’t see how this should work (as long as the `nonce` value is not static). Well, virtually everything that’s wrong can be found in the web, so this shouldn’t be a guideline…
* I will revise our current implementation of HTTP Client 1 to conform to the specified behavior. After that, I should be aware of the implications that need to be considered.
* Regarding our current spec, I will create another minor pull request to state more precisely what is going to happen if the supplied authentication data is incomplete (username, but no password, how to handle an empty username; etc.).

**Comment by ChristianGruen** [comment]
…finally merged. Sorry for the delay.

**Pull request merged**
