### PR TITLE
HTTP Responses: Multipart messages

### PR DESCRIPTION
**Pull request by ChristianGruen**
I have dropped my editor notes, as I believe we should keep response handling as simple and as flexible as possible.

### CODE REVIEW

**Comment by adamretter** [comment]
Hi @ChristianGruen I need a bit of time to read and think about the existing Response Body stuff before I review this PR. You might have noticed that I have been ignoring it until we get the request stuff solid ;-)

**Comment by ChristianGruen** [comment]
No problem; thanks, take your time ;)

**Comment by ChristianGruen** [comment]
I have fixed a minor conflict; it should now be possible to merge the pull request.

**Comment by adamretter** [comment]
@ChristianGruen This looks good thanks. Sorry for the delay. I am going to merge it.

I have an idea about how we can slightly improve on `parse-response-entity-body (xs:boolean)` to offer more flexibility to the user. I will send a PR to start that discussion ;-)

**Pull request merged**
