### PR TITLE
Administrative work

### PR DESCRIPTION
**Pull request by claudius108**
Upgraded version of kubera-expath-plugin, and restored a version as I discussed with Florent.

### CODE REVIEW

**Comment by claudius108** [comment]
Happy New Year!

Is someone willing to review this PR, please?

Thanks,
Claudius

**Comment by adamretter** [comment]
@claudius108 Hi there and Happy New Year.

I could help maybe... Apart from restoring specs, this seems to bump the plugin version from 0.4.8 to 0.5.9 is the pom.xml, but I don't see any actual changes to the plugin, is this intentional?

**Comment by claudius108** [comment]
Yes, I did only restoring of spec, and bumping the expath plugin version from 0.4.8 to 0.5.9. Nothing else.

Thank you

**Comment by claudius108** [comment]
Thank you.

**Pull request merged**
