### PR TITLE
Refactored the crypto 1.0

### PR DESCRIPTION
**Pull request by claudius108**

### CODE REVIEW

**Comment by michaelhkay** [comment]
I regret that I don't understand the technical detail well enough to make well informed comments, but a couple of editorial points:

(a) the reference to Functions and Operators 1.1 is to a working draft: should it refer to 3.0? (Actually, I don't see where this reference is used.)

(b) in other EXPath specs we've been moving to meaningful error codes, e.g. crypto:algorithmNotSupported.

(c) crypto:generate-signature has an argument which is an XPath expression. Should say what version of XPath this must conform to; and state what assumptions can be made about its static and dynamic context.

Michael Kay
Saxonica
mike@saxonica.com
+44 (0) 118 946 5893

**Comment by ChristianGruen** [comment]
Hi Cladius, here are some more, hopefully helpful, comments to the new draft of your Crypto Module

**Message Digests**

* It's nice to have a function added for computing hash values
* Also refers to `crypto:hmac`: Instead of providing a `$format` argument, I think it could be more appropriate to return xs:base64Binary or xs:hexBinary instead of xs:string, which can then be converted to the other type. In the other EXPath modules, base64 is used as the de-facto standard for binary data. In the case of hash values, however, this is possibly not the most intuitive format.

**Generate Signatures**

* I appreciate that you updated the previously ambiguous signatures of `crypto:generate-signature`
* From the map definitions, it is not always obvious what happens if options are missing or if their values are invalid (e.g.: `signature-namespace-prefix`, `signature-type`, `iv`, …)
* The syntax of the `$references` option looks pretty complex to me. I assume you plan to add more documentation on what it's supposed to do?
* If the value of `$references` can be more than one node, the map argument must be updated to `$parameters as map(xs:string, item()+)?`

**Error Codes**

* I like that the error codes have become more readable. But I would welcome if the number of different codes could be reduced. Otherwise, a simple code snippet will potentially need to be wrapped with 5 or more catch clauses, and this may be more confusing than helpful. Beside that, I would tend to remove the redundant "-error" substrings from the codes. Some examples:
  * `crypto:canonicalization-algorithm-error`, `crypto:digest-algorithm-error`, `crypto:signature-algorithm-error` could be summarized as `crypto:unknown-algorithm`.
  * I would raise the same error if an unknown algorithm is supplied for other functions like `crypto:hash` (instead of `crypto:algorithm-or-transformation-error`)`
  * Maybe some of the codes can be kept shorter, as they are usually accompanied by an additional string message.
* Can `$data` really be an arbitrary node type (including `attribute()` or `comment()`)?

**General**

* Many of the listed references are not quoted (yet?) in the text

**Comment by ChristianGruen** [comment]
After all, this new version of the spec is a good step forward, so I'd be happy seeing it merged. @fgeorges: What do you think?

**Comment by michaelhkay** [comment]
Ohh, I think I may have been reviewing the wrong version... Sorry.

Michael Kay
Saxonica
mike@saxonica.com
+44 (0) 118 946 5893

**Comment by ChristianGruen** [comment]
This is the latest one: https://raw.githubusercontent.com/claudius108/expath-cg/master/specs/crypto/crypto.html

**Comment by claudius108** [comment]
Hi, Mike,


Thank you for the suggestions.

Did you looked at crypto.xml / crypto.html? These represents the latest
draft for the version 1.0.


Thanks,
Claudius

On Sun, Feb 22, 2015 at 4:01 PM, Michael Kay <notifications@github.com>
wrote:

> I regret that I don't understand the technical detail well enough to make
> well informed comments, but a couple of editorial points:
>
> (a) the reference to Functions and Operators 1.1 is to a working draft:
> should it refer to 3.0? (Actually, I don't see where this reference is
> used.)
>
> (b) in other EXPath specs we've been moving to meaningful error codes,
> e.g. crypto:algorithmNotSupported.
>
> (c) crypto:generate-signature has an argument which is an XPath
> expression. Should say what version of XPath this must conform to; and
> state what assumptions can be made about its static and dynamic context.
>
> Michael Kay
> Saxonica
> mike@saxonica.com
> +44 (0) 118 946 5893
>
>
>
>
> On 21 Feb 2015, at 10:13, claudius108 <notifications@github.com> wrote:
>
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/expath/expath-cg/pull/66
> >
> > Commit Summary
> >
> > Improved the bibliography of the crypto spec.
> > Improved the abstract of the crypto spec.
> > Added normative id-s for the error messages.
> > Added canonical values for error messages' keys.
> > Improved the introduction section.
> > Added the correct namespace for error messages.
> > Added pom file to the spec crypto.
> > Regenerated the crypto spec.
> > Simplified the introduction.
> > Improved the section 'Integrity and Authentication of Data'.
> > Improved the 'Integrity and Authentication of Data' section.
> > Finished the 'Digital Signature' section.
> > Updated the error list.
> > Updated the bibliographic references list.
> > Updated the 'Encryption and Decryption' section.
> > Finished the 'Encryption and Decryption' section.
> > Formatted the function signatures and renamed some parameters.
> > File Changes
> >
> > A specs/crypto/.gitignore (1)
> > M specs/crypto/crypto-20150214.xml (474)
> > M specs/crypto/crypto.html (911)
> > M specs/crypto/crypto.xml (474)
> > A specs/crypto/pom.xml (45)
> > Patch Links:
> >
> > https://github.com/expath/expath-cg/pull/66.patch
> > https://github.com/expath/expath-cg/pull/66.diff
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expath/expath-cg/pull/66#issuecomment-75439209>.
>



-- 
http://kuberam.ro
http://kuberam.ro/art

**Comment by claudius108** [comment]
Hi, Christian,

Thank you for the suggestions.

I do have some answers below.

On Sun, Feb 22, 2015 at 8:46 PM, Christian Gruen <notifications@github.com>
wrote:

> Hi Cladius, here are some more, hopefully helpful, comments to the new
> draft of your Crypto Module
>
> *Message Digests*
>
>    - It's nice to have a function added for computing hash values
>    - Also refers to crypto:hmac: Instead of providing a $format argument,
>    I think it could be more appropriate to return xs:base64Binary or
>    xs:hexBinary instead of xs:string, which can then be converted to the other
>    type. In the other EXPath modules, base64 is used as the de-facto standard
>    for binary data. In the case of hash values, however, this is possibly not
>    the most intuitive format.
>
> This functions it is supposed to return the result as  base64 string, as
it is stated in its description. So, the return data type has to be
xs:string, I guess.


>
> *Generate Signatures*
>
>    - I appreciate that you updated the previously ambiguous signatures of
>    crypto:generate-signature
>    - From the map definitions, it is not always obvious what happens if
>    options are missing or if their values are invalid (e.g.:
>    signature-namespace-prefix, signature-type, iv, …)
>
> I will add details.


>
>    - The syntax of the $references option looks pretty complex to me. I
>    assume you plan to add more documentation on what it's supposed to do?
>
> I will add details.

>
>    - If the value of $references can be more than one node, the map
>    argument must be updated to $parameters as map(xs:string, item()+)?
>
> Fixed this, thanks.


>    -
>
> *Error Codes*
>
>    - I like that the error codes have become more readable. But I would
>    welcome if the number of different codes could be reduced. Otherwise, a
>    simple code snippet will potentially need to be wrapped with 5 or more
>    catch clauses, and this may be more confusing than helpful. Beside that, I
>    would tend to remove the redundant "-error" substrings from the codes. Some
>    examples:
>       - crypto:canonicalization-algorithm-error,
>       crypto:digest-algorithm-error, crypto:signature-algorithm-error
>       could be summarized as crypto:unknown-algorithm.
>       - I would raise the same error if an unknown algorithm is supplied
>       for other functions like crypto:hash (instead of
>       crypto:algorithm-or-transformation-error)`
>       - Maybe some of the codes can be kept shorter, as they are usually
>       accompanied by an additional string message.
>
> Good suggestions, thanks.

>
>    -
>        - Can $data really be an arbitrary node type (including attribute()
>    or comment())?
>
> Functions like crypto:hmac(), crypto:hash(), crypto:encrypt(),
crupto:decrypt() could be used for the value/contents of an attribute() /
comment(), as this is xs:string.

>
>
> *General*
>
>    - Many of the listed references are not quoted (yet?) in the text
>
> Well, I kind of added what I used to learn and improve my knowledge in
this field. I will try to add references to what it is possible.

Claudius


>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expath/expath-cg/pull/66#issuecomment-75453615>.
>



-- 
http://kuberam.ro
http://kuberam.ro/art

**Comment by claudius108** [comment]
Hi, all,

Thank you for all the comments, now I think I have covered them all.

Claudius

**Comment by joewiz** [comment]
@claudius108 I see a number of commits in this pull request related to the mongodb project.  Are these commits intended to be part of this pull request?  Or is this just an unintended artifact of a git merge?

**Comment by claudius108** [comment]
Hm, they are not mine.

**Comment by joewiz** [comment]
Maybe you should rebase the branch of your commit against the current master?

**Comment by claudius108** [comment]
They are gone now, thanks.

**Comment by joewiz** [comment]
Great, nice git work, Claudius - that's not a straightforward operation!

@michaelhkay Since you had submitted several comments, would you care to review Claudius's revisions? @ChristianGruen previously indicated his support of the merge. Also, @fgeorges?

**Comment by ChristianGruen** [comment]
@joewiz: I'll be happy to review the changes (it may only happen next week, though..).

**Comment by ChristianGruen** [comment]
Hi Claudius, here is some feedback (I'm quoting my initial comments):

> Also refers to crypto:hmac: Instead of providing a $format argument, I think it could be more appropriate to return xs:base64Binary or xs:hexBinary instead of xs:string, which can then be converted to the other type. In the other EXPath modules, base64 is used as the de-facto standard for binary data.

I see that instead of returning `xs:base64Binary`, you decided to keep the `$format` argument. What were your thoughts on my initial comment?

> From the map definitions, it is not always obvious what happens if options are missing or if their values are invalid (e.g.: signature-namespace-prefix, signature-type, iv, …)

There may still be some open questions here. An example: What is supposed to happen if `crypt:decrypt` is called and `iv` is a) not specified, or b) an empty sequence is specified?

>> Can $data really be an arbitrary node type (including attribute()
    or comment())?
> Functions like crypto:hmac(), crypto:hash(), crypto:encrypt(), crupto:decrypt() could be used for the value/contents of an attribute() / comment(), as this is xs:string.

So what would happen if e.g. a comment is specified as argument for crypto:generate-signature? Is it an error, or does the result simply make no sense?

Here are some new comments on `crypto:encrypt` and `crypto:decrypt`:

1. If a string is encoded with `crypto:encrypt`, I guess that a string is to be returned (right?). However, I believe that the encoded string may contain characters that are not valid in XML, so I may be a better solution to always return the result as `xs:base64binary`.
2. When a padding mechanism is "not available, this is an error [crypto:inexistent-padding]". How can this mechanism be made available? The same observation applies to the [crypto:incorrect-padding] error.
3. Which cryptographic algorithms are to be supported here? What are possible values? Is there a minimum set?

A minor editorial issue: One of the references seems to invalid: "For details regarding these parameters, see the table ??? below.".

And last but not least, to have some more examples (for both the implementor as well as the user of the module)..

Hope this helps,
Christian

**Comment by claudius108** [comment]
Hi,

Thanks for suggestions. I hope that I managed to implement needed changes.

Also, I do have an answer:

Question: Functions like crypto:hmac(), crypto:hash(), crypto:encrypt(), crupto:decrypt() could be used for the value/contents of an attribute() / comment(), as this is xs:string.

Answer: Only if the xs:string() constructor function is used with them:
xs:string(@attribute),
xs:string(comment {'text'}).

Claudius

**Comment by joewiz** [comment]
Exciting! Thanks, @claudius108!

**Pull request merged**
