### PR TITLE
Refactored the HTTP Response Sections

### PR DESCRIPTION
**Pull request by adamretter**
So no major changes here. Just minor wordy stuff. I tried to bring some of the language closer to the HTTP spec, just like we did for the request sections.

### CODE REVIEW

**Comment by ChristianGruen** [comment]
Looks splendid at first sight! I hope I can look at it in more depth tomorrow. Thank you.

**Comment by ChristianGruen** [comment]
Finally some feedback, and a few suggestions:

* In version 1 of the spec, the HTTP response contained `status` and `message` attributes. In the PR, the keys of the response map are called `status-code` and `reason-phrase`. I think that the old naming was intuitive enough, so I would stick with the existing wording to reduce the number of inconsistencies between the two versions, and to make life of upgraders easier. My personal impression is that “message” is even more common today, even if “reason phrase” was the wording that was used in the initial spec. – If we decide to adopt the changes, we’d probably need to update all examples in order to reflect the changes.
* I saw you simplified the media type pattern for XML types (`application/xml-external-parsed-entity` → `application/xml*`). `application/xml-dtd` (and possibly other types) would then be interpreted as XML as well. Maybe we should stick with the patterns from version 1.0 (which have been adopted from other specs, as far as I can judge), or add some explanatory details to the description to keep the table small?
* We could rename `http:network-error` to `http:network`, as the reason for error codes are always errors (otherwise, we might need to rename `http:parse` to `http:parse-error`, etc.).
* And a similar suggestion (feel free to ignore it): `http-version` could be renamed to `version`, because it’s all about HTTP anyway. But maybe that would introduce incompatibilities to the extensions that you had added to version 1.0?

**Comment by adamretter** [comment]
1. Regards `status-code` and `reason-phrase`, I used those because those are the terms in the actual HTTP 1.1 RFC. I felt it was better to be closer to the source spec than to create our own names for things. I am not religious about this though. Happy to change it if you would still like me too?

2. Regards the media type patterns, I naively assumed that all patterns starting `application/xml-` would have XML content. My bad. DTD which has `application/xml-dtd` as you pointed out is not going to work here. I will fix this.

3. Agreed. I will change `http:network-error` to `http:network`.

4. I personally don't care about backwards compatibility! I could rename `http-version` could be renamed to `version`. Although, could then perhaps `version` be misinterpreted as meaning the version of the request options map spec, and/or the response map spec? What do you think?

**Comment by ChristianGruen** [comment]
1. If it’s ok for you indeed, I would prefer the old wording.
4. Yes, that could actually happen if we decide to introduce such an option in future, you are right. I can sleep fine, no matter which variant we choose ;)

**Comment by adamretter** [comment]
1. Okay done :-)
2. Let's leave it as is... i.e. `http-version`

**Comment by adamretter** [comment]
Hooray :-)

**Comment by fgeorges** [comment]
@adamretter For ref, the full story of the "XML Media Types" is on the 1.0 spec: http://expath.org/spec/http-client#d2e578

**Pull request merged**
