### PR TITLE
http-client2 → http-client-2

### PR DESCRIPTION
**Pull request by ChristianGruen**

### CODE REVIEW

**Comment by ChristianGruen** [comment]
The rename was motivated by Florent..

> Tiny suggestion: would it be possible to rename it to "http-client-2", for the sake of consistency?

**Comment by adamretter** [comment]
Okay I see. @fgeorges just wondering what we are striving to be consistent with? I don't see any other version numbers in specs. Are you simply referring to using hyphens on word boundaries?

**Comment by joewiz** [comment]
@adamretter I was wondering the same, then noticed the use of hyphens before version numbers in other W3C XML-related specs:

- https://www.w3.org/TR/xquery-31/
- https://www.w3.org/TR/xpath-functions-31/
- https://www.w3.org/TR/xslt-xquery-serialization-31/

**Comment by adamretter** [comment]
@joewiz Ahh! Maybe that's it then?

**Comment by ChristianGruen** [comment]
Makes sense!

**Comment by fgeorges** [comment]
Yes, that's the common usage (TR specs and word boundaries)

**Review by danhduykhan-code — APPROVED** [review]

**Pull request merged**
